#!/bin/bash
dinghy up
tab2='cd ~/Git/quiz_api && dcu -d && && open http://api.quiz.docker'
new_tab "quiz_api SERVER" "$tab2"
# new terminal tab
tab3='cd ~/Git/quiz_web && dcu web && open http://quiz.docker'
new_tab "quiz_web SERVER" "$tab3"


#if you see `Error: ENOENT: no such file or directory, stat '/usr/src/app/dist/index.html' at Error (native)`
#ctrl-c to kill it
#docker-compose run --rm web npm run generate-index
